# Name of your application. Used to uniquely configure containers.
service: desinghrajan

# Name of the container image.
image: desinghrajan/desinghrajan

# Deploy to these servers.
servers:
  web:
    hosts:
      - 139.84.144.43
    options:
      publish:
        - "3000:80"

# Build configuration
builder:
  arch:
    - amd64

# No proxy configuration - deploy containers directly

# Credentials for your image host.
registry:
  # Using Docker Hub
  username: desinghrajan
  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    # Run the Solid Queue Supervisor inside the web server's Puma process to do jobs.
    SOLID_QUEUE_IN_PUMA: true

    # Set number of cores available to the application (1 vCPU on your Vultr server)
    WEB_CONCURRENCY: 1
