# Name of your application. Used to uniquely configure containers.
service: desinghrajan

# Name of the container image.
image: desinghrajan/desinghrajan

# Deploy to these servers.
servers:
  web:
    hosts:
      - 139.84.144.43

# Build configuration
builder:
  arch:
    - amd64

# Let Kamal handle everything with its built-in proxy
proxy:
  ssl: true
  host: desinghrajan.in

# Credentials for your image host.
registry:
  # Using Docker Hub
  username: desinghrajan
  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    # Single process for portfolio site - no workers needed
    WEB_CONCURRENCY: 0

    # Optimize for low memory usage
    RAILS_ENV: production
    RAILS_MAX_THREADS: 5
